/**
 * País / demônimo em qualquer idioma comum de passaporte → código ICAO.
 * Saída no manifesto: sempre NAT[code] em espanhol (constants.js).
 *
 * Cobertura: América, Europa, Ásia, África, Oceania — nomes de país e
 * gentílicos em EN/ES/PT/FR/DE/IT/NL + formas locais frequentes.
 */
export const COUNTRY_ALIASES = {
  BRA: [
    'BRASIL', 'BRAZIL', 'BRAZILIAN', 'BRASILEIRA', 'BRASILEIRO', 'BRASILENA', 'BRASILENO',
    'BRESIL', 'BRESILIEN', 'BRESILIENNE', 'BRASILIANISCH', 'BRASILIANER', 'BRASILIANERIN',
    'BRASILE', 'BRASILIANO', 'BRASILIANA', 'BRAZILIE', 'BRAZILIAAN'
  ],
  ARG: [
    'ARGENTINA', 'ARGENTINE', 'ARGENTINO', 'ARGENTINIAN', 'ARGENTINIEN', 'ARGENTINISCH',
    'ARGENTINIENNE', 'ARGENTINIEN'
  ],
  PRY: ['PARAGUAY', 'PARAGUAYA', 'PARAGUAYO', 'PARAGUAYAN', 'PARAGUAI', 'PARAGUAYEN', 'PARAGUAIEN'],
  URY: ['URUGUAY', 'URUGUAYA', 'URUGUAYO', 'URUGUAYAN', 'URUGUAI', 'URUGUAYEN'],
  CHL: ['CHILE', 'CHILENA', 'CHILENO', 'CHILEAN', 'CHILIEN', 'CHILIENNE', 'CHILEENS'],
  BOL: ['BOLIVIA', 'BOLIVIANA', 'BOLIVIANO', 'BOLIVIAN', 'BOLIVIEN', 'BOLIVIE'],
  PER: ['PERU', 'PERUANA', 'PERUANO', 'PERUVIAN', 'PERUVIEN', 'PERUVIENNE', 'PEROU'],
  COL: ['COLOMBIA', 'COLOMBIANA', 'COLOMBIANO', 'COLOMBIAN', 'COLOMBIEN', 'COLOMBIE'],
  VEN: ['VENEZUELA', 'VENEZOLANA', 'VENEZOLANO', 'VENEZUELAN', 'VENEZUELIEN', 'VENEZUELIENNE'],
  ECU: ['ECUADOR', 'ECUATORIANA', 'ECUATORIANO', 'ECUADORIAN', 'EQUATORIEN', 'EQUATEUR'],
  USA: [
    'USA', 'AMERICAN', 'AMERICANA', 'AMERICANO', 'ESTADOUNIDENSE', 'UNITEDSTATES',
    'UNITED STATES', 'UNITED STATES OF AMERICA', 'ETATSUNIS', 'ETATS UNIS',
    'ESTADOSUNIDOS', 'ESTADOS UNIDOS', 'AMERIKAAN', 'USAMERIKANISCH'
  ],
  CAN: ['CANADA', 'CANADIENSE', 'CANADIAN', 'CANADIEN', 'CANADIENNE', 'KANADA', 'KANADIER'],
  MEX: ['MEXICO', 'MEXICANA', 'MEXICANO', 'MEXICAN', 'MEXIQUE', 'MEXIKANISCH', 'MESSICO'],
  CUB: ['CUBA', 'CUBANA', 'CUBANO', 'CUBAN', 'CUBAIN', 'CUBAINE'],
  DOM: ['DOMINICAN', 'DOMINICANA', 'DOMINICANO', 'DOMINICAINE', 'REPUBLICADOMINICANA'],
  HTI: ['HAITI', 'HAITIANA', 'HAITIANO', 'HAITIAN', 'HAITIEN', 'HAITIENNE'],
  PAN: ['PANAMA', 'PANAMENA', 'PANAMENO', 'PANAMANIAN', 'PANAMEEN'],
  CRI: ['COSTARICA', 'COSTA RICA', 'COSTARRICENSE', 'COSTARICAN', 'COSTARICAIN'],
  NIC: ['NICARAGUA', 'NICARAGUENSE', 'NICARAGUAN'],
  HND: ['HONDURAS', 'HONDURENA', 'HONDURENO', 'HONDURAN'],
  SLV: ['ELSALVADOR', 'EL SALVADOR', 'SALVADORENA', 'SALVADORENO', 'SALVADORAN'],
  GTM: ['GUATEMALA', 'GUATEMALTECA', 'GUATEMALTECO', 'GUATEMALAN'],
  BLZ: ['BELIZE', 'BELICENA', 'BELIZEAN'],
  JAM: ['JAMAICA', 'JAMAICANA', 'JAMAICAN'],
  TTO: ['TRINIDAD', 'TRINIDADANDTOBAGO', 'TRINITENSE'],
  GUY: ['GUYANA', 'GUYANESA', 'GUYANESE'],
  SUR: ['SURINAME', 'SURINAMESA', 'SURINAMESE'],
  ITA: [
    'ITALIA', 'ITALY', 'ITALIANA', 'ITALIANO', 'ITALIAN', 'ITALIEN', 'ITALIENNE',
    'ITALIENISCH', 'ITALIAAN'
  ],
  ESP: [
    'ESPANA', 'SPAIN', 'ESPANOLA', 'ESPANOL', 'SPANISH', 'ESPAGNE', 'ESPAGNOL', 'ESPAGNOLE',
    'SPANIEN', 'SPANISCH', 'SPAGNA', 'SPAGNOLO', 'SPANJE'
  ],
  PRT: [
    'PORTUGAL', 'PORTUGUESA', 'PORTUGUES', 'PORTUGUESE', 'PORTUGAISE', 'PORTUGAIS',
    'PORTUGIESISCH', 'PORTOGALLO'
  ],
  DEU: [
    'GERMANY', 'ALEMANA', 'ALEMAN', 'ALEMANHA', 'GERMAN', 'DEUTSCHLAND', 'DEUTSCHE',
    'DEUTSCHER', 'DEUTSCH', 'ALLEMAGNE', 'ALLEMAND', 'ALLEMANDE', 'GERMANIA', 'TEDESCO',
    'DUITSLAND', 'DUITS'
  ],
  FRA: [
    'FRANCE', 'FRANCESA', 'FRANCES', 'FRENCH', 'FRANCAIS', 'FRANCAISE',
    'FRANZOSISCH', 'FRANZOESISCH', 'FRANKREICH', 'FRANCIA', 'FRANCESE', 'FRANKRIJK'
  ],
  GBR: [
    'BRITISH', 'BRITANICA', 'BRITANICO', 'INGLESA', 'INGLES', 'ENGLISH',
    'UNITEDKINGDOM', 'UNITED KINGDOM', 'GREATBRITAIN', 'GREAT BRITAIN',
    'ROYAUMEUNI', 'ROYAUME UNI', 'UK', 'BRITANNIQUE', 'BRITANNIQUE',
    'ENGLAND', 'ANGLETERRE', 'INGLATERRA', 'GROSSBRITANNIEN', 'VERENIGDKONINKRIJK'
  ],
  IRL: ['IRELAND', 'IRLANDESA', 'IRLANDES', 'IRISH', 'IRLANDE', 'IRLAND', 'EIRE', 'IRLANDA'],
  NLD: [
    'NETHERLANDS', 'HOLANDA', 'HOLANDESA', 'HOLANDES', 'DUTCH', 'NEERLANDESA', 'NEERLANDES',
    'PAYSBAS', 'PAYS BAS', 'NEDERLAND', 'NEDERLANDSE', 'PAYS-BAS', 'HOLLANDE', 'OLANDA'
  ],
  BEL: ['BELGIUM', 'BELGA', 'BELGIAN', 'BELGIQUE', 'BELGE', 'BELGIEN', 'BELGIE', 'BELGIO'],
  CHE: [
    'SWITZERLAND', 'SUIZA', 'SUIZO', 'SWISS', 'SUISSE', 'SCHWEIZ', 'SCHWEIZER',
    'SVIZZERA', 'HELVETIA', 'ZWITSERLAND'
  ],
  AUT: ['AUSTRIA', 'AUSTRIACA', 'AUSTRIACO', 'AUSTRIAN', 'AUTRICHE', 'OSTERREICH', 'ÖSTERREICH'],
  POL: ['POLAND', 'POLACA', 'POLACO', 'POLISH', 'POLSKA', 'POLOGNE', 'POLEN', 'POLONIA', 'POOLS'],
  UKR: ['UKRAINE', 'UCRANIANA', 'UCRANIANO', 'UKRAINIAN', 'UKRAINIEN', 'UKRAINE', 'UCRAINA', 'UKRAINA'],
  ROU: ['ROMANIA', 'RUMANA', 'RUMANO', 'ROMANIAN', 'ROUMAIN', 'ROUMANIE', 'RUMANIEN', 'ROMANIA'],
  TUR: ['TURKEY', 'TURCA', 'TURCO', 'TURKISH', 'TURQUIE', 'TURC', 'TURKIYE', 'TÜRKIYE', 'TURCHIA'],
  GRC: ['GREECE', 'GRIEGA', 'GRIEGO', 'GREEK', 'GRECE', 'GREC', 'GRIECHENLAND', 'GRECIA', 'ELLADA'],
  CZE: ['CZECH', 'CHECA', 'CHECO', 'CZECHIA', 'TCHEQUE', 'TCHEQUIE', 'TSCHECHIEN', 'CESKO', 'CZECH REPUBLIC'],
  SVK: ['SLOVAKIA', 'ESLOVACA', 'ESLOVACO', 'SLOVAK', 'SLOVAQUIE', 'SLOWAKEI', 'SLOVENSKO'],
  HUN: ['HUNGARY', 'HUNGARA', 'HUNGARO', 'HUNGARIAN', 'HONGRIE', 'UNGARN', 'UNGHERIA', 'MAGYAR'],
  SWE: ['SWEDEN', 'SUECA', 'SUECO', 'SWEDISH', 'SUEDE', 'SCHWEDEN', 'SVERIGE', 'SVEZIA'],
  NOR: ['NORWAY', 'NORUEGA', 'NORUEGO', 'NORWEGIAN', 'NORVEGE', 'NORWEGEN', 'NORGE', 'NORVEGIA'],
  DNK: ['DENMARK', 'DANESA', 'DANES', 'DANISH', 'DANEMARK', 'DANEMARK', 'DANMARK', 'DANIA', 'DANISH'],
  FIN: ['FINLAND', 'FINLANDESA', 'FINLANDES', 'FINNISH', 'FINLANDE', 'FINNLAND', 'SUOMI', 'FINLANDIA'],
  ISL: ['ICELAND', 'ISLANDESA', 'ICELANDIC', 'ISLANDE', 'ISLAND', 'ISLANDIA'],
  EST: ['ESTONIA', 'ESTONIA', 'ESTONIAN', 'ESTONIEN', 'ESTLAND', 'EESTI'],
  LVA: ['LATVIA', 'LETONA', 'LATVIAN', 'LETTONIE', 'LETTLAND', 'LATVIJA'],
  LTU: ['LITHUANIA', 'LITUANA', 'LITHUANIAN', 'LITUANIE', 'LITAUEN', 'LIETUVA'],
  BGR: ['BULGARIA', 'BULGARA', 'BULGARIAN', 'BULGARIE', 'BULGARIEN'],
  HRV: ['CROATIA', 'CROATA', 'CROATIAN', 'CROATIE', 'KROATIEN', 'HRVATSKA'],
  SRB: ['SERBIA', 'SERBIA', 'SERBIAN', 'SERBIE', 'SERBIEN', 'SRBIJA'],
  BIH: ['BOSNIA', 'BOSNIAANDHERZEGOVINA', 'BOSNIACA', 'BOSNIAN', 'BOSNIE'],
  MKD: ['NORTHMACEDONIA', 'MACEDONIA', 'MACEDONIAN', 'MACEDOINE'],
  MNE: ['MONTENEGRO', 'MONTENEGRINA', 'MONTENEGRIN'],
  ALB: ['ALBANIA', 'ALBANESA', 'ALBANIAN', 'ALBANIE'],
  SVN: ['SLOVENIA', 'ESLOVENA', 'SLOVENIAN', 'SLOVENIE', 'SLOWENIEN', 'SLOVENIJA'],
  LUX: ['LUXEMBOURG', 'LUXEMBURGUESA', 'LUXEMBOURGISH', 'LUXEMBURGO'],
  MLT: ['MALTA', 'MALTESA', 'MALTESE'],
  CYP: ['CYPRUS', 'CHIPRIOTA', 'CYPRIOT', 'CHYPRE'],
  AND: ['ANDORRA', 'ANDORRANA', 'ANDORRAN'],
  MCO: ['MONACO', 'MONEGASCA', 'MONEGASQUE'],
  LIE: ['LIECHTENSTEIN', 'LIECHTENSTEINER'],
  SMR: ['SANMARINO', 'SAN MARINO'],
  RUS: [
    'RUSSIA', 'RUSSIAN', 'RUSA', 'RUSO', 'RUSSIE', 'RUSSE', 'RUSSLAND', 'ROSSIYA',
    'FEDERACIONRUSA', 'RUSSIAN FEDERATION'
  ],
  BLR: ['BELARUS', 'BIELORRUSA', 'BELARUSIAN', 'BIELORUSSIE', 'WEISSRUSSLAND'],
  MDA: ['MOLDOVA', 'MOLDAVA', 'MOLDOVAN', 'MOLDAVIE'],
  GEO: ['GEORGIA', 'GEORGIANA', 'GEORGIAN', 'GEORGIE'],
  ARM: ['ARMENIA', 'ARMENIA', 'ARMENIAN', 'ARMENIE'],
  AZE: ['AZERBAIJAN', 'AZERBAIYANA', 'AZERBAIJANI', 'AZERBAIDJAN'],
  KAZ: ['KAZAKHSTAN', 'KAZAJA', 'KAZAKH', 'KAZAKHSTAN'],
  UZB: ['UZBEKISTAN', 'UZBEKA', 'UZBEK'],
  JPN: [
    'JAPAN', 'JAPONESA', 'JAPONES', 'JAPANESE', 'JAPON', 'JAPONAIS', 'JAPONAISE',
    'JAPANER', 'GIAPPONE', 'NIHON', 'NIPPON'
  ],
  CHN: [
    'CHINA', 'CHINESE', 'CHINOISE', 'CHINOIS', 'CHINESA', 'CHINES', 'CHINESISCH',
    'CINA', 'PRC', 'PEOPLESREPUBLICOFCHINA'
  ],
  TWN: ['TAIWAN', 'TAIWANESE', 'TAIWANESA', 'TAIWANAIS', 'CHINESATAIPEI', 'TAIPEI'],
  HKG: ['HONGKONG', 'HONG KONG', 'HONGKONESA', 'HONGKONGER'],
  KOR: [
    'KOREA', 'KOREAN', 'COREANA', 'COREANO', 'COREE', 'COREE DUSUD', 'SOUTHKOREA',
    'REPUBLICOFKOREA', 'COREA', 'SUIDKOREA'
  ],
  PRK: ['NORTHKOREA', 'COREADELNORTE', 'DPRK'],
  IND: ['INDIA', 'INDIAN', 'INDIANA', 'INDIANO', 'INDIEN', 'INDIENNE', 'INDIEN'],
  PAK: ['PAKISTAN', 'PAKISTANI', 'PAQUISTANI'],
  BGD: ['BANGLADESH', 'BANGLADESI', 'BANGLADESHI'],
  LKA: ['SRILANKA', 'SRI LANKA', 'CEILANESA', 'SRI LANKAN'],
  NPL: ['NEPAL', 'NEPALESA', 'NEPALESE'],
  THA: ['THAILAND', 'TAILANDESA', 'THAI', 'THAILANDAISE', 'THAILANDE', 'THAILANDIA'],
  VNM: ['VIETNAM', 'VIETNAMITA', 'VIETNAMESE', 'VIETNAMIEN', 'VIET NAM'],
  IDN: ['INDONESIA', 'INDONESIAN', 'INDONESIEN', 'INDONESIENNE', 'INDONESIE'],
  MYS: ['MALAYSIA', 'MALASIA', 'MALAYSIAN', 'MALAISIE', 'MALAYSIA'],
  SGP: ['SINGAPORE', 'SINGAPURENSE', 'SINGAPOURIEN', 'SINGAPUR', 'SINGAPOREAN'],
  PHL: ['PHILIPPINES', 'FILIPINA', 'FILIPINO', 'PHILIPPINE', 'FILIPINAS', 'PHILIPPINES'],
  KHM: ['CAMBODIA', 'CAMBOYANA', 'CAMBODIAN', 'CAMBODGE'],
  LAO: ['LAOS', 'LAOSIANA', 'LAOTIAN', 'LAO'],
  MMR: ['MYANMAR', 'BIRMANIA', 'BURMESE', 'BURMA'],
  MNG: ['MONGOLIA', 'MONGOLA', 'MONGOLIAN'],
  ISR: ['ISRAEL', 'ISRAELI', 'ISRAELIEN', 'ISRAELIENNE', 'ISRAELI'],
  PSE: ['PALESTINE', 'PALESTINA', 'PALESTINIAN', 'PALESTINIEN'],
  LBN: ['LEBANON', 'LIBANESA', 'LEBANESE', 'LIBAN', 'LIBANO'],
  JOR: ['JORDAN', 'JORDANA', 'JORDANIAN', 'JORDANIE'],
  SYR: ['SYRIA', 'SIRIA', 'SYRIAN', 'SYRIE'],
  IRQ: ['IRAQ', 'IRAQUI', 'IRAQI', 'IRAK'],
  IRN: ['IRAN', 'IRANI', 'IRANIAN', 'IRANIEN'],
  AFG: ['AFGHANISTAN', 'AFGANA', 'AFGHAN'],
  SAU: ['SAUDI', 'SAUDIARABIA', 'SAUDI ARABIA', 'SAOUDIEN', 'ARABIA SAUDI', 'SAUDIARABIEN'],
  ARE: [
    'UAE', 'EMIRATI', 'EMIRATIE', 'EMIRATS', 'UNITEDARABEMIRATES',
    'UNITED ARAB EMIRATES', 'EMIRATOSARABES', 'EMIRATS ARABES UNIS'
  ],
  QAT: ['QATAR', 'CATARI', 'QATARI'],
  KWT: ['KUWAIT', 'KUWAITI', 'KOWEIT'],
  BHR: ['BAHRAIN', 'BAHREINI', 'BAHREIN'],
  OMN: ['OMAN', 'OMANI', 'OMANAISE'],
  YEM: ['YEMEN', 'YEMENI', 'YEMENITE'],
  EGY: ['EGYPT', 'EGIPCIA', 'EGIPCIO', 'EGYPTIAN', 'EGYPTE', 'AGYPTO', 'MISR'],
  MAR: ['MOROCCO', 'MARROQUI', 'MOROCCAN', 'MAROC', 'MAROCAIN', 'MAROKKO'],
  DZA: ['ALGERIA', 'ARGELINA', 'ALGERIAN', 'ALGERIE'],
  TUN: ['TUNISIA', 'TUNECINA', 'TUNISIAN', 'TUNISIE'],
  LBY: ['LIBYA', 'LIBIA', 'LIBYAN', 'LIBYE'],
  SDN: ['SUDAN', 'SUDANESA', 'SUDANESE'],
  ZAF: [
    'SOUTHAFRICA', 'SOUTH AFRICA', 'SUDAFRICANA', 'SUDAFRICANO', 'SOUTH AFRICAN',
    'AFRIQUEDUSUD', 'SUIDAFRIKA'
  ],
  NGA: ['NIGERIA', 'NIGERIANA', 'NIGERIAN'],
  GHA: ['GHANA', 'GHANESA', 'GHANAIAN'],
  KEN: ['KENYA', 'KENIANA', 'KENYAN'],
  ETH: ['ETHIOPIA', 'ETIOPE', 'ETHIOPIAN', 'ETHIOPIE'],
  TZA: ['TANZANIA', 'TANZANA', 'TANZANIAN'],
  UGA: ['UGANDA', 'UGANDESA', 'UGANDAN'],
  SEN: ['SENEGAL', 'SENEGALESA', 'SENEGALESE', 'SENEGALAIS'],
  CIV: ['COTEDIVOIRE', 'IVORYCOAST', 'MARFILENA', 'IVORIAN', 'COTE D IVOIRE'],
  CMR: ['CAMEROON', 'CAMERUNESA', 'CAMEROONIAN', 'CAMEROUN'],
  AGO: ['ANGOLA', 'ANGOLENA', 'ANGOLAN'],
  MOZ: ['MOZAMBIQUE', 'MOZAMBIQUENA', 'MOZAMBICAN'],
  CPV: ['CAPEVERDE', 'CABOVERDE', 'CABOVERDIANA'],
  AUS: ['AUSTRALIA', 'AUSTRALIANA', 'AUSTRALIANO', 'AUSTRALIAN', 'AUSTRALIEN', 'AUSTRALIENNE'],
  NZL: ['NEWZEALAND', 'NEW ZEALAND', 'NEOZELANDESA', 'NEOZELANDES', 'NEW ZEALANDER', 'NOUVELLEZELANDE'],
  FJI: ['FIJI', 'FIYIANA', 'FIJIAN'],
  PNG: ['PAPUANEWGUINEA', 'PAPUA', 'PAPUA NEW GUINEA']
};

/** Flatten aliases → NAT_WORDS map (chave já foldável). */
export function buildNatWords() {
  const out = Object.create(null);
  for (const [code, aliases] of Object.entries(COUNTRY_ALIASES)) {
    for (const raw of aliases) {
      const key = String(raw)
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .toUpperCase()
        .replace(/[^A-Z0-9]/g, '');
      if (key.length >= 3) out[key] = code;
    }
  }
  return out;
}
